language: php
dist: trusty
sudo: false

cache:
  yarn: true
  directories:
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

branches:
  only:
    - master
    - develop
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=5.0 WP_MULTISITE=1 PHPCS=1 CHECKJS=1 PHPUNIT=1 SECURITY=1 TRAVIS_NODE_VERSION=node
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.6
      env: PHPUNIT=1 WP_VERSION=4.8
    - php: 7.0
      env: PHPUNIT=1 WP_VERSION=4.9
    - php: "7.4snapshot"
      env: PHPUNIT=1 WP_VERSION=master

  allow_failures:
    # Allow failures for unstable builds.
    - php: "7.4snapshot"
    - env: WP_VERSION=master

before_install:
- export SECURITYCHECK_DIR=/tmp/security-checker
- if [[ "$CHECKJS" == "1" ]]; then nvm install $TRAVIS_NODE_VERSION; fi
- if [[ "$CHECKJS" == "1" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
- if [[ "$CHECKJS" == "1" ]]; then export PATH=$HOME/.yarn/bin:$PATH; fi

install:
- if [[ "$PHPUNIT" == "1" ]]; then composer install --no-interaction; fi
- if [[ "$CHECKJS" == "1" ]]; then yarn global add grunt-cli; fi
- if [[ "$CHECKJS" == "1" ]]; then yarn install; fi
- if [[ "$SECURITY" == "1" ]]; then wget -P $SECURITYCHECK_DIR https://get.sensiolabs.org/security-checker.phar && chmod +x $SECURITYCHECK_DIR/security-checker.phar;fi

before_script:
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    PLUGIN_SLUG=$(basename $(pwd))
    export WP_DEVELOP_DIR=/tmp/wordpress/
    git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    cd ..
    cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    cd /tmp/wordpress/
    cp wp-tests-config-sample.php wp-tests-config.php
    sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    sed -i "s/yourpasswordhere//" wp-tests-config.php
    mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    phpenv rehash
  fi

script:
# Exclude tests directory from linting for PHP 5.2/3
- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then if find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -path ./tests -prune -o -name '*.php' -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
- if [[ $TRAVIS_PHP_VERSION != "5.2" && $TRAVIS_PHP_VERSION != "5.3" ]]; then if find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
# Run PHPCS separately for the plugin files and the test files.
- if [[ "$PHPCS" == "1" ]]; then composer check-cs; fi
- if [[ "$CHECKJS" == "1" ]]; then grunt check; fi
- if [[ "$PHPUNIT" == "1" ]]; then composer test; fi
- if [[ $TRAVIS_PHP_VERSION == "5.3" || $TRAVIS_PHP_VERSION == "7.3" ]]; then composer validate --no-check-all; fi
# Check for known security vulnerabilities in the currently locked-in dependencies.
- if [[ "$SECURITY" == "1" ]]; then php $SECURITYCHECK_DIR/security-checker.phar -n security:check $(pwd)/composer.lock;fi
